version: 2

registries:
  gpr:
    type: rubygems-server
    url: "https://rubygems.pkg.github.com/justalemon"
    username: justalemon
    password: ${{ secrets.BUNDLE_RUBYGEMS__PKG__GITHUB__COM }}

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule: 
      interval: daily
    labels:
      - "priority: p3 low"
      - "type: dependencies"
      - "status: acknowledged"
  - package-ecosystem: bundler
    directory: /
    registries: "*"
    schedule: 
      interval: daily
    labels:
      - "priority: p3 low"
      - "type: dependencies"
      - "status: acknowledged"
