name: Build Action
on:
  - push

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.2.0
      - name: Select Node Version
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 19
          cache: npm
      - name: Install Dependencies
        run: npm install
      - name: Build with tsc
        run: npm run build
      - name: Copy files to dist folder
        run: mkdir dist && cp index.html dist && cp script.js dist && cp script.js.map dist && cp styles.css dist && cp projects.json dist
      - name: Upload the artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: site
          path: dist
          if-no-files-found: error
  deploy:
    runs-on: ubuntu-22.04
    needs:
      - build
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3.0.1
        with:
          name: site
          path: .
      - name: Set up the Pages environment
        uses: actions/configure-pages@v2.1.3
      - name: Upload the new artifact for Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: .
      - name: Deploy site
        uses: actions/deploy-pages@v1.2.3
