name: Build Action
on:
  - push

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.2.0
      - name: Select Node Version
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 19
          cache: npm
      - name: Install Dependencies
        run: npm install
      - name: Build with tsc
        run: npm run build
      - name: Copy files to dist folder
        run: mkdir dist && cp index.html dist && cp script.js dist && cp script.js.map dist && cp styles.css dist && cp projects.json dist
      - name: Upload the artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: site
          path: dist
          if-no-files-found: error
